name: google_sign_in_dartio
description: Flutter package for Google Sign-In built in dart and support both Mobile and Desktop environments.
version: 0.2.2
homepage: https://github.com/long1eu/google_sign_in_dart
commit: 89794a635a5efad6705e3d7ccc29e8139318d947

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.0
  google_sign_in_platform_interface: ^2.0.1
  shared_preferences: ^2.0.8
  shared_preferences_foundation: ^2.1.2
  shared_preferences_linux: ^2.0.2
  url_launcher: ^6.0.12
  url_launcher_macos: ^2.0.2
  meta: ^1.7.0
  crypto: ^3.0.1
  http: ^0.13.3
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/main.dart
  - /example/web/index.html